roles:
  # https://galaxy.ansible.com/ui/standalone/roles/escalate/common/
  - name: common
    src: escalate.common
    version: v2.1.0

collections:
  # https://galaxy.ansible.com/ui/repo/published/community/general/
  - name: community.general
    version: 11.2.1
