roles:
  # https://galaxy.ansible.com/escalate/common
  - name: common
    src: escalate.common
    version: v1.6.0

collections:
  # https://galaxy.ansible.com/community/general
  - name: community.general
    version: 3.3.2
